---
- hosts: localhost
  tasks:
    - name: Create Cognitive Services instance
      azure_rm_cognitiveservicesaccount:
        resource_group: myResourceGroup
        name: myCognitiveService
        sku_name: S0
        kind: TextAnalytics
        location: eastus
        state: present
      register: cognitive_service

    - name: Print Cognitive Services endpoint
      debug:
        msg: "Cognitive Services endpoint: {{ cognitive_service.endpoint }}"